apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  labels:
    app: alertmanager
spec:
  type: LoadBalancer
  ports:
    - port: 9093
      targetPort: 9093
  selector:
    app: alertmanager
