apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: monitor-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "10Gi"  # Wrap in quotes